-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public._bot_message_ids (
  message_id text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT _bot_message_ids_pkey PRIMARY KEY (message_id)
);
CREATE TABLE public.acquisition_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  strategy jsonb NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'failed'::text])),
  channels_launched jsonb DEFAULT '[]'::jsonb,
  total_prospects integer DEFAULT 0,
  total_conversions integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  started_at timestamp with time zone DEFAULT now(),
  next_optimization_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT acquisition_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT acquisition_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ad_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  platform text NOT NULL,
  campaign_name text NOT NULL,
  budget numeric NOT NULL,
  targeting jsonb,
  ad_copy jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text])),
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  conversions integer DEFAULT 0,
  cost_spent numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ad_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT ad_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.agent_pending_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  business_id uuid NOT NULL,
  question text NOT NULL,
  options ARRAY,
  response text,
  responded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  CONSTRAINT agent_pending_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT agent_pending_approvals_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.agent_tasks(id),
  CONSTRAINT agent_pending_approvals_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.agent_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'paused'::text, 'waiting_approval'::text, 'waiting_subtask'::text])),
  goal text NOT NULL,
  role text,
  steps_used integer NOT NULL DEFAULT 0,
  tool_log jsonb DEFAULT '[]'::jsonb,
  result text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  parent_task_id uuid,
  messages jsonb,
  owner_phone text,
  enabled_tools jsonb,
  plan_dag jsonb,
  CONSTRAINT agent_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT agent_tasks_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT agent_tasks_parent_task_id_fkey FOREIGN KEY (parent_task_id) REFERENCES public.agent_tasks(id)
);
CREATE TABLE public.agent_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  cron_expression text NOT NULL,
  assistant_name text NOT NULL DEFAULT 'Chief of Staff'::text,
  goal_template text NOT NULL,
  enabled_tools ARRAY DEFAULT '{}'::text[],
  timezone text NOT NULL DEFAULT 'Europe/Madrid'::text,
  active boolean NOT NULL DEFAULT true,
  last_run_at timestamp with time zone,
  next_run_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT agent_workflows_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  type character varying NOT NULL,
  icon character varying,
  message text NOT NULL,
  details text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_activities_pkey PRIMARY KEY (id),
  CONSTRAINT ai_activities_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_budget_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  event_type text NOT NULL,
  operation text,
  estimated_cost numeric,
  current_cost numeric,
  daily_budget numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_budget_events_pkey PRIMARY KEY (id),
  CONSTRAINT ai_budget_events_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_business_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  plan jsonb NOT NULL,
  goals jsonb,
  status character varying DEFAULT 'draft'::character varying,
  confidence_score numeric,
  expected_revenue numeric,
  adaptation_count integer DEFAULT 0,
  last_adapted timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT ai_business_plans_pkey PRIMARY KEY (id),
  CONSTRAINT ai_business_plans_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_cofounder_state (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  state jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_cofounder_state_pkey PRIMARY KEY (id),
  CONSTRAINT ai_cofounder_state_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_conversations (
  id character varying NOT NULL,
  business_id uuid,
  participant_id character varying,
  participant_type character varying,
  conversation_data jsonb NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  outcome jsonb,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_conversations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_edges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  source_id uuid,
  target_id uuid,
  relation character varying NOT NULL,
  properties jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_edges_pkey PRIMARY KEY (id),
  CONSTRAINT ai_edges_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT ai_edges_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.ai_nodes(id),
  CONSTRAINT ai_edges_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.ai_nodes(id)
);
CREATE TABLE public.ai_event_counters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  date date NOT NULL,
  counters jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_event_counters_pkey PRIMARY KEY (id),
  CONSTRAINT ai_event_counters_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_experiment_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid,
  variant_id character varying,
  expected_impact jsonb,
  actual_impact jsonb,
  applied_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_experiment_applications_pkey PRIMARY KEY (id),
  CONSTRAINT ai_experiment_applications_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.ai_experiments(id)
);
CREATE TABLE public.ai_experiment_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  experiment jsonb NOT NULL,
  priority character varying DEFAULT 'medium'::character varying,
  parent_experiment_id uuid,
  executed boolean DEFAULT false,
  queued_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_experiment_queue_pkey PRIMARY KEY (id),
  CONSTRAINT ai_experiment_queue_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT ai_experiment_queue_parent_experiment_id_fkey FOREIGN KEY (parent_experiment_id) REFERENCES public.ai_experiments(id)
);
CREATE TABLE public.ai_experiments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  name character varying NOT NULL,
  hypothesis text,
  type character varying,
  variants jsonb NOT NULL,
  tracking jsonb,
  allocation jsonb,
  status character varying DEFAULT 'draft'::character varying,
  confidence_threshold numeric DEFAULT 0.95,
  minimum_sample_size integer DEFAULT 1000,
  winner character varying,
  results jsonb,
  interim_results jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_experiments_pkey PRIMARY KEY (id),
  CONSTRAINT ai_experiments_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_learning_patterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  pattern_type character varying,
  condition jsonb,
  action jsonb,
  outcome jsonb,
  success_rate numeric,
  confidence numeric,
  application_count integer DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_learning_patterns_pkey PRIMARY KEY (id),
  CONSTRAINT ai_learning_patterns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_llm_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  state_hash character varying NOT NULL,
  llm_response jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_llm_cache_pkey PRIMARY KEY (id),
  CONSTRAINT ai_llm_cache_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_memories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  content text NOT NULL,
  category character varying,
  embedding USER-DEFINED,
  importance_score numeric DEFAULT 0.5,
  success_indicator boolean,
  context jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  archived boolean DEFAULT false,
  memory_timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  use_count integer DEFAULT 0,
  last_recalled_at timestamp with time zone,
  recall_count integer NOT NULL DEFAULT 0,
  outcome text,
  validated_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_memories_pkey PRIMARY KEY (id),
  CONSTRAINT ai_memories_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_memories_simple (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  key text NOT NULL,
  value jsonb NOT NULL,
  importance numeric DEFAULT 0.5,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_memories_simple_pkey PRIMARY KEY (id),
  CONSTRAINT ai_memories_simple_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_nodes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  label character varying NOT NULL,
  name character varying NOT NULL,
  properties jsonb DEFAULT '{}'::jsonb,
  embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_nodes_pkey PRIMARY KEY (id),
  CONSTRAINT ai_nodes_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_playbooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action_type text NOT NULL,
  title text NOT NULL,
  playbook_data jsonb NOT NULL,
  source_patterns_count integer DEFAULT 0,
  confidence_score numeric DEFAULT 0.5,
  usage_count integer DEFAULT 0,
  success_rate numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_playbooks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  date date NOT NULL,
  total_cost numeric DEFAULT 0,
  operation_count integer DEFAULT 0,
  operations jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_usage_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.assistants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL DEFAULT 'AI Sales Assistant'::text,
  tone text NOT NULL DEFAULT 'friendly'::text,
  goal text NOT NULL DEFAULT 'book_consultation'::text,
  system_prompt text,
  custom_rules ARRAY DEFAULT '{}'::text[],
  knowledge_base jsonb DEFAULT '{}'::jsonb,
  tools_enabled ARRAY DEFAULT '{send_checkout_link,book_calendar,send_template,transfer_to_human}'::text[],
  sequence_steps jsonb DEFAULT '[]'::jsonb,
  trigger_config jsonb DEFAULT '{}'::jsonb,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT assistants_pkey PRIMARY KEY (id),
  CONSTRAINT assistants_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.blast_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['topup'::text, 'blast'::text, 'bonus'::text, 'refund'::text])),
  amount numeric NOT NULL,
  recipient_count integer,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blast_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT blast_transactions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_id uuid,
  slot_date date NOT NULL,
  slot_time text NOT NULL,
  slot_label text,
  status text NOT NULL DEFAULT 'pending'::text,
  booking_type text NOT NULL DEFAULT 'customer'::text,
  customer_name text,
  customer_phone text,
  customer_address text,
  estimate text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.business_integrations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  service_name text NOT NULL,
  description text,
  base_url text NOT NULL,
  api_key_encrypted text,
  auth_type text DEFAULT 'bearer'::text,
  auth_header text DEFAULT 'Authorization'::text,
  status text DEFAULT 'active'::text,
  config jsonb DEFAULT '{}'::jsonb,
  requested_by text DEFAULT 'owner'::text,
  request_context text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT business_integrations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  revenue numeric DEFAULT 0,
  customers integer DEFAULT 0,
  conversion_rate numeric DEFAULT 0,
  avg_order_value numeric DEFAULT 0,
  traffic integer DEFAULT 0,
  metrics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT business_metrics_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_proof_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  subdomain text NOT NULL UNIQUE,
  metrics jsonb NOT NULL,
  sales_data jsonb DEFAULT '[]'::jsonb,
  testimonials jsonb DEFAULT '[]'::jsonb,
  verification_status text DEFAULT 'unverified'::text CHECK (verification_status = ANY (ARRAY['unverified'::text, 'verified'::text, 'stripe_verified'::text])),
  verified_revenue numeric,
  last_verified timestamp with time zone,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT business_proof_pages_pkey PRIMARY KEY (id),
  CONSTRAINT business_proof_pages_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  would_recommend boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT business_reviews_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT business_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.business_success_predictions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  success_probability numeric NOT NULL,
  projected_revenue numeric NOT NULL,
  projected_timeframe_days integer,
  based_on_patterns integer,
  confidence_level text,
  recommendations jsonb,
  actual_outcome numeric,
  prediction_accuracy numeric,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  CONSTRAINT business_success_predictions_pkey PRIMARY KEY (id),
  CONSTRAINT business_success_predictions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  business_type text NOT NULL,
  industry text NOT NULL,
  proven_revenue numeric NOT NULL,
  success_rate numeric NOT NULL,
  time_to_first_sale integer NOT NULL,
  guarantee_confidence numeric NOT NULL,
  business_model jsonb NOT NULL,
  marketing_playbook jsonb NOT NULL,
  operational_requirements jsonb NOT NULL,
  success_metrics jsonb NOT NULL,
  risk_factors jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'draft'::text, 'deprecated'::text])),
  usage_count integer DEFAULT 0,
  actual_performance jsonb,
  last_performance_update timestamp with time zone,
  last_confidence_update timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  subdomain text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'generating'::text, 'ready'::text, 'failed'::text, 'prospect'::text])),
  session_id text UNIQUE,
  phone_number text,
  completed_onboarding boolean DEFAULT false,
  launch_date timestamp with time zone,
  trial_ends_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  form_data jsonb NOT NULL,
  business_data jsonb,
  views integer DEFAULT 0,
  first_sale_date timestamp with time zone,
  total_revenue numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_sale_date timestamp with time zone,
  growth_data jsonb,
  latest_campaign_review jsonb,
  latest_email_campaign jsonb,
  latest_email_batch jsonb,
  opportunity_data jsonb,
  total_leads integer DEFAULT 0,
  total_visitors integer DEFAULT 0,
  projected_revenue numeric DEFAULT 0,
  last_growth_campaign_at timestamp with time zone,
  guarantee_start_at timestamp with time zone,
  first_payment_at timestamp with time zone,
  guarantee_48h_status text DEFAULT 'pending'::text CHECK (guarantee_48h_status = ANY (ARRAY['pending'::text, 'met'::text, 'missed'::text, 'paid'::text])),
  guarantee_60d_status text DEFAULT 'pending'::text CHECK (guarantee_60d_status = ANY (ARRAY['pending'::text, 'met'::text, 'extended'::text, 'failed'::text])),
  guarantee_last_checked_at timestamp with time zone,
  guarantee_48h_payout_id text,
  guarantee_48h_payout_amount numeric DEFAULT 100,
  plan_tier text DEFAULT 'starter'::text CHECK (plan_tier = ANY (ARRAY['starter'::text, 'pro'::text, 'scale'::text])),
  rev_share_percent numeric DEFAULT 0,
  stripe_connect_account_id text,
  work_free_mode boolean DEFAULT false,
  model text,
  assets jsonb,
  strategy_plan jsonb,
  email_ramp_stage integer DEFAULT 0,
  manual_approval_required boolean DEFAULT true,
  approved_at timestamp with time zone,
  ai_objections_handled integer DEFAULT 0,
  ai_response_rate numeric DEFAULT 0.00,
  ai_conversation_count integer DEFAULT 0,
  template_id uuid,
  ai_agent_enabled boolean DEFAULT true,
  revenue_share_suspended boolean DEFAULT false,
  revenue_share_suspended_reason text,
  guarantee_id uuid,
  paid_plan_session_id character varying,
  available_balance numeric DEFAULT 0,
  gross_sales_since_cashout numeric DEFAULT 0,
  booking_url text,
  expires_at timestamp with time zone,
  source text DEFAULT 'wizard'::text,
  whatsapp_notify_number text,
  notify_preference text DEFAULT 'whatsapp'::text,
  whatsapp_api_config jsonb,
  whatsapp_number text,
  blast_credits numeric DEFAULT 0,
  blast_credits_used numeric DEFAULT 0,
  slot_settings jsonb DEFAULT '{"slots": [{"id": "morning", "end": "11:00", "label": "9am - 11am", "start": "09:00"}, {"id": "early_afternoon", "end": "15:00", "label": "1pm - 3pm", "start": "13:00"}, {"id": "late_afternoon", "end": "17:00", "label": "3pm - 5pm", "start": "15:00"}], "days_ahead": 3, "buffer_hours": 2}'::jsonb,
  whatsapp_template_feedback text,
  prospecting_config jsonb,
  outreach_paused boolean DEFAULT false,
  automation_rules jsonb DEFAULT '[]'::jsonb,
  active boolean DEFAULT false,
  ai_provider text,
  ai_model text,
  CONSTRAINT businesses_pkey PRIMARY KEY (id),
  CONSTRAINT businesses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT businesses_guarantee_id_fkey FOREIGN KEY (guarantee_id) REFERENCES public.revenue_guarantees(id),
  CONSTRAINT businesses_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id),
  CONSTRAINT fk_paid_plan_session FOREIGN KEY (paid_plan_session_id) REFERENCES public.platform_subscriptions(stripe_session_id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text,
  sent_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.cart_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  customer_email text,
  customer_name text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_amount numeric DEFAULT 0,
  last_activity_at timestamp with time zone DEFAULT now(),
  abandoned_at timestamp with time zone,
  recovery_emails_sent integer DEFAULT 0,
  recovered boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT cart_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.cashout_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'usd'::text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  processor text DEFAULT 'stripe'::text,
  processor_transaction_id text,
  requested_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  completed_at timestamp with time zone,
  payment_method_details jsonb,
  failure_reason text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cashout_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT cashout_transactions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.chat_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone text NOT NULL,
  business_id uuid,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
  content text NOT NULL,
  tool_calls jsonb,
  created_at timestamp with time zone DEFAULT now(),
  fts tsvector DEFAULT to_tsvector('english'::regconfig, COALESCE(content, ''::text)),
  CONSTRAINT chat_history_pkey PRIMARY KEY (id),
  CONSTRAINT chat_history_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.clicks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  email_id uuid,
  business_id uuid NOT NULL,
  campaign_id uuid,
  dest_url text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clicks_pkey PRIMARY KEY (id),
  CONSTRAINT clicks_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT clicks_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id),
  CONSTRAINT clicks_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.conversion_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  session_id text,
  event_type text NOT NULL,
  product_id uuid,
  customer_email text,
  value numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversion_events_pkey PRIMARY KEY (id),
  CONSTRAINT conversion_events_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT conversion_events_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.conversion_intelligence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_type text NOT NULL,
  industry text NOT NULL,
  query_hash text NOT NULL UNIQUE,
  top_strategies jsonb NOT NULL,
  timing_insights jsonb,
  message_insights jsonb,
  cache_expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  hit_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  last_accessed timestamp with time zone DEFAULT now(),
  CONSTRAINT conversion_intelligence_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_email text NOT NULL,
  note text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT customer_notes_pkey PRIMARY KEY (id),
  CONSTRAINT customer_notes_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.customer_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_email text NOT NULL,
  tag text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_tags_pkey PRIMARY KEY (id),
  CONSTRAINT customer_tags_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.customer_testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  customer_email text NOT NULL,
  customer_name text NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  testimonial_text text NOT NULL,
  order_id uuid,
  verified boolean DEFAULT false,
  verification_method text,
  created_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  CONSTRAINT customer_testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT customer_testimonials_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  email text NOT NULL,
  first_name text,
  last_name text,
  phone text,
  total_spent numeric DEFAULT 0,
  order_count integer DEFAULT 0,
  first_order_date timestamp with time zone,
  last_order_date timestamp with time zone,
  lifetime_value numeric DEFAULT 0,
  accepts_marketing boolean DEFAULT true,
  marketing_source text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email_sequence_day integer DEFAULT 1,
  email_sequence_started_at timestamp with time zone,
  next_email_at timestamp with time zone,
  last_email_sent_at timestamp with time zone,
  email_sequence_completed_at timestamp with time zone,
  status text DEFAULT 'lead'::text,
  source text DEFAULT 'unknown'::text,
  name text,
  notes text,
  tags ARRAY,
  service_count integer DEFAULT 0,
  last_service_date timestamp with time zone,
  next_reminder_due timestamp with time zone,
  reminder_preference text DEFAULT 'sms'::text CHECK (reminder_preference = ANY (ARRAY['sms'::text, 'whatsapp'::text, 'both'::text, 'none'::text])),
  building_name text,
  area text,
  is_repeat_customer boolean DEFAULT false,
  lifetime_services integer DEFAULT 0,
  referral_code text UNIQUE,
  referred_by uuid,
  blast_optout boolean DEFAULT false,
  last_blast_at timestamp with time zone,
  last_outbound_type text,
  last_outbound_at timestamp with time zone,
  last_service_record_id uuid,
  last_interaction_context text,
  wa_instance_id uuid,
  ai_paused_until timestamp with time zone,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_last_service_record_id_fkey FOREIGN KEY (last_service_record_id) REFERENCES public.service_records(id),
  CONSTRAINT customers_wa_instance_id_fkey FOREIGN KEY (wa_instance_id) REFERENCES public.whatsapp_instances(id),
  CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT customers_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES public.customers(id)
);
CREATE TABLE public.demo_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone text NOT NULL,
  owner_name text NOT NULL,
  business_name text,
  business_id text,
  step text NOT NULL DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  outcome text,
  stripe_session_id text,
  fallback_sent boolean DEFAULT false,
  CONSTRAINT demo_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.discount_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  code text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['percentage'::text, 'fixed_amount'::text])),
  value numeric NOT NULL,
  minimum_order_amount numeric DEFAULT 0,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_codes_pkey PRIMARY KEY (id),
  CONSTRAINT discount_codes_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.email_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  prospect_email text NOT NULL,
  message_type text NOT NULL CHECK (message_type = ANY (ARRAY['initial'::text, 'objection'::text, 'ai_response'::text, 'follow_up'::text])),
  content text NOT NULL,
  objection_type text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT email_conversations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.email_outreach (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  prospect_id character varying NOT NULL,
  email_type character varying NOT NULL,
  subject character varying,
  content text,
  status character varying DEFAULT 'sent'::character varying,
  sent_at timestamp with time zone,
  response_received boolean DEFAULT false,
  meeting_scheduled boolean DEFAULT false,
  converted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_outreach_pkey PRIMARY KEY (id),
  CONSTRAINT email_outreach_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.email_replies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_id uuid,
  business_id uuid NOT NULL,
  from_email text,
  body text,
  sentiment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_replies_pkey PRIMARY KEY (id),
  CONSTRAINT email_replies_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT email_replies_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id)
);
CREATE TABLE public.emails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_id uuid,
  to_email text NOT NULL,
  subject text,
  provider text,
  provider_message_id text,
  bounce boolean DEFAULT false,
  complaint boolean DEFAULT false,
  suppressed boolean DEFAULT false,
  clicked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT emails_pkey PRIMARY KEY (id),
  CONSTRAINT emails_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT emails_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.follow_up_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  prospect_email text NOT NULL,
  objection_type text,
  follow_up_date timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text, 'failed'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT follow_up_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT follow_up_tasks_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.fulfillment_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  content_type text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  access_count integer DEFAULT 0,
  last_accessed_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillment_content_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillment_content_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.fulfillment_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback_text text,
  improvement_suggestions text,
  would_recommend boolean,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillment_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillment_feedback_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.fulfillment_followups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  follow_up_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'completed'::text, 'skipped'::text])),
  scheduled_for timestamp with time zone NOT NULL,
  sent_at timestamp with time zone,
  response_received boolean DEFAULT false,
  response_content text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillment_followups_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillment_followups_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.fulfillments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  fulfillment_type text NOT NULL,
  delivered_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_value numeric DEFAULT 0,
  completed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillments_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillments_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.golden_state_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  image_url text NOT NULL,
  label text,
  category text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT golden_state_images_pkey PRIMARY KEY (id),
  CONSTRAINT golden_state_images_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.growth_experiments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  experiment_type character varying NOT NULL,
  experiment_data jsonb NOT NULL,
  status character varying DEFAULT 'running'::character varying,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  results jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT growth_experiments_pkey PRIMARY KEY (id),
  CONSTRAINT growth_experiments_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.growth_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_type text NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'failed'::text])),
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  metrics jsonb DEFAULT '{"conversions": 0, "leads_generated": 0, "revenue_generated": 0}'::jsonb,
  CONSTRAINT growth_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT growth_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.guarantee_emergency_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  revenue_target numeric NOT NULL,
  strategies jsonb NOT NULL,
  activated_at timestamp with time zone NOT NULL,
  deactivated_at timestamp with time zone,
  results jsonb,
  success boolean,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT guarantee_emergency_actions_pkey PRIMARY KEY (id),
  CONSTRAINT guarantee_emergency_actions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.guarantee_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  payout_id text NOT NULL,
  amount numeric NOT NULL,
  reason text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  stripe_payout_id text,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT guarantee_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT guarantee_payouts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.hunter_prospects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_name text NOT NULL,
  service_type text NOT NULL,
  area text NOT NULL,
  whatsapp_number text NOT NULL,
  owner_name text,
  website_url text,
  facebook_url text,
  google_maps_url text,
  instagram_url text,
  notes text,
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['facebook'::text, 'google_maps'::text, 'instagram'::text, 'referral'::text, 'manual'::text, 'other'::text])),
  pain_signals ARRAY DEFAULT '{}'::text[],
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'opener_queued'::text, 'opener_sent'::text, 'replied'::text, 'preview_sent'::text, 'follow_up_1'::text, 'follow_up_2'::text, 'follow_up_3'::text, 'closed_won'::text, 'closed_lost'::text, 'archived'::text, 'no_whatsapp'::text])),
  preview_business_id uuid,
  preview_url text,
  created_at timestamp with time zone DEFAULT now(),
  opener_sent_at timestamp with time zone,
  replied_at timestamp with time zone,
  preview_sent_at timestamp with time zone,
  last_follow_up_at timestamp with time zone,
  closed_at timestamp with time zone,
  created_by uuid,
  email text,
  raw_context text,
  priority integer NOT NULL DEFAULT 0,
  wa_instance_id uuid,
  CONSTRAINT hunter_prospects_pkey PRIMARY KEY (id),
  CONSTRAINT hunter_prospects_wa_instance_id_fkey FOREIGN KEY (wa_instance_id) REFERENCES public.whatsapp_instances(id),
  CONSTRAINT hunter_prospects_preview_business_id_fkey FOREIGN KEY (preview_business_id) REFERENCES public.businesses(id),
  CONSTRAINT hunter_prospects_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.idempotency (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT idempotency_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inngest_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  job_type character varying NOT NULL,
  event_name character varying NOT NULL,
  event_data jsonb NOT NULL,
  status character varying DEFAULT 'queued'::character varying,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inngest_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT inngest_jobs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  title text,
  status text DEFAULT 'draft'::text,
  description text,
  materials_needed jsonb DEFAULT '[]'::jsonb,
  quotes_received jsonb DEFAULT '[]'::jsonb,
  blockers jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.knowledge_base_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  document_id uuid NOT NULL,
  document_title text NOT NULL,
  chunk_index integer NOT NULL DEFAULT 0,
  chunk_text text NOT NULL,
  embedding USER-DEFINED,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT knowledge_base_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_base_chunks_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.landing_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  page_data jsonb NOT NULL,
  variant_id character varying,
  is_active boolean DEFAULT false,
  performance_metrics jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT landing_pages_pkey PRIMARY KEY (id),
  CONSTRAINT landing_pages_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL DEFAULT 'Unknown'::text,
  phone text,
  email text,
  website text,
  address text,
  category text,
  notes text,
  source text DEFAULT 'agent'::text,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'converted'::text, 'lost'::text, 'archived'::text])),
  rating numeric,
  reviews_count integer,
  google_maps_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketing_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  campaign_data jsonb NOT NULL,
  channel character varying NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketplace_listings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  platform text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  pricing jsonb NOT NULL,
  tags ARRAY,
  status text DEFAULT 'pending_approval'::text CHECK (status = ANY (ARRAY['pending_approval'::text, 'active'::text, 'paused'::text, 'rejected'::text])),
  orders_received integer DEFAULT 0,
  total_earnings numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketplace_listings_pkey PRIMARY KEY (id),
  CONSTRAINT marketplace_listings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.mcp_servers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  transport text NOT NULL DEFAULT 'http'::text,
  url text NOT NULL,
  api_key text,
  headers jsonb DEFAULT '{}'::jsonb,
  enabled boolean NOT NULL DEFAULT true,
  tool_filter ARRAY,
  cached_tools jsonb,
  cached_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mcp_servers_pkey PRIMARY KEY (id),
  CONSTRAINT mcp_servers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.onboarding_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  event_name text NOT NULL,
  event_properties jsonb NOT NULL DEFAULT '{}'::jsonb,
  timestamp timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid,
  product_name text NOT NULL,
  product_price numeric NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_email text NOT NULL,
  customer_name text,
  customer_phone text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'fulfilled'::text, 'refunded'::text, 'abandoned'::text])),
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  shipping_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  stripe_session_id text UNIQUE,
  cart_token text UNIQUE,
  abandoned_at timestamp with time zone,
  recovery_email_sent_at timestamp with time zone,
  recovered_at timestamp with time zone,
  shipping_address jsonb,
  billing_address jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.outreach_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_type text NOT NULL,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'completed'::text])),
  total_prospects integer DEFAULT 0,
  email_templates jsonb,
  metrics jsonb DEFAULT '{"sent": 0, "opened": 0, "clicked": 0, "replied": 0}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  last_batch_sent_at timestamp with time zone,
  CONSTRAINT outreach_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT outreach_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.pattern_triggers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  pattern_id text NOT NULL,
  pattern_name text NOT NULL,
  severity text NOT NULL,
  counters jsonb,
  triggered_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pattern_triggers_pkey PRIMARY KEY (id),
  CONSTRAINT pattern_triggers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.platform_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_email character varying NOT NULL,
  user_name character varying,
  plan character varying NOT NULL CHECK (plan::text = ANY (ARRAY['professional'::character varying, 'scale'::character varying, 'pro'::character varying, 'vip'::character varying, 'starter'::character varying]::text[])),
  amount numeric NOT NULL,
  currency character varying DEFAULT 'usd'::character varying,
  stripe_session_id character varying NOT NULL UNIQUE,
  payment_status character varying DEFAULT 'completed'::character varying,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT platform_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.playbook_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  playbook_id uuid NOT NULL,
  results jsonb,
  success_rate numeric,
  applied_at timestamp with time zone DEFAULT now(),
  CONSTRAINT playbook_applications_pkey PRIMARY KEY (id),
  CONSTRAINT playbook_applications_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT playbook_applications_playbook_id_fkey FOREIGN KEY (playbook_id) REFERENCES public.ai_playbooks(id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  product_id uuid,
  order_id uuid,
  customer_email text NOT NULL,
  customer_name text,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  content text,
  verified_purchase boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  approved boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT product_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  compare_at_price numeric,
  inventory_count integer DEFAULT 999,
  sales_count integer DEFAULT 0,
  conversion_rate numeric DEFAULT 0.00,
  image_url text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'draft'::text, 'archived'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  plan text DEFAULT 'trial'::text CHECK (plan = ANY (ARRAY['trial'::text, 'starter'::text, 'growth'::text, 'scale'::text])),
  phone_number text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sms_notifications_enabled boolean DEFAULT true,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.prospects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name character varying,
  email character varying,
  company character varying,
  industry character varying,
  company_size character varying,
  linkedin_url text,
  title character varying,
  source character varying,
  status character varying DEFAULT 'discovered'::character varying,
  contacted_at timestamp with time zone,
  last_response_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  last_objection_type text,
  last_ai_response text,
  objection_count integer DEFAULT 0,
  conversation_count integer DEFAULT 0,
  platform text CHECK (platform = ANY (ARRAY['reddit'::text, 'facebook'::text, 'linkedin'::text, 'twitter'::text, 'instagram'::text, 'email'::text])),
  platform_username text,
  platform_user_id text,
  profile_url text,
  engagement_score integer DEFAULT 0 CHECK (engagement_score >= 0 AND engagement_score <= 100),
  conversion_status text DEFAULT 'discovered'::text CHECK (conversion_status = ANY (ARRAY['discovered'::text, 'contacted'::text, 'engaged'::text, 'qualified'::text, 'converted'::text, 'lost'::text])),
  last_engagement timestamp with time zone,
  contact_attempts integer DEFAULT 0,
  notes text,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  total_value numeric DEFAULT 0,
  CONSTRAINT prospects_pkey PRIMARY KEY (id),
  CONSTRAINT prospects_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.public_metrics (
  id text NOT NULL,
  metrics jsonb NOT NULL,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT public_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quote_chat_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT quote_chat_history_pkey PRIMARY KEY (id),
  CONSTRAINT quote_chat_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.quote_leads(id)
);
CREATE TABLE public.quote_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  quote_amount numeric NOT NULL,
  job_type text NOT NULL,
  contractor_id text,
  status text NOT NULL DEFAULT 'Open'::text CHECK (status = ANY (ARRAY['Open'::text, 'Called'::text, 'WhatsApp_Nurture'::text, 'Booked'::text, 'Lost'::text])),
  call_sid text,
  call_outcome text,
  whatsapp_thread_id text,
  stripe_payment_link text,
  retell_call_id text,
  next_action_time timestamp with time zone NOT NULL DEFAULT (now() + '48:00:00'::interval),
  attempts integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  business_id uuid,
  currency text NOT NULL DEFAULT 'USD'::text,
  source text NOT NULL DEFAULT 'webhook'::text,
  sequence_step integer NOT NULL DEFAULT 0,
  sequence_paused boolean NOT NULL DEFAULT false,
  paused_until timestamp with time zone,
  timezone text NOT NULL DEFAULT 'America/New_York'::text,
  last_reply_at timestamp with time zone,
  sequence_completed boolean NOT NULL DEFAULT false,
  breakup_reply text,
  CONSTRAINT quote_leads_pkey PRIMARY KEY (id),
  CONSTRAINT quote_leads_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  referrer_id uuid NOT NULL,
  referral_code text NOT NULL,
  referee_id uuid,
  referee_phone text,
  referee_name text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'clicked'::text, 'registered'::text, 'booked'::text, 'completed'::text, 'expired'::text])),
  referrer_discount_percent integer DEFAULT 10,
  referee_discount_percent integer DEFAULT 10,
  referrer_reward_applied boolean DEFAULT false,
  referee_reward_applied boolean DEFAULT false,
  link_clicked_at timestamp with time zone,
  registered_at timestamp with time zone,
  booked_at timestamp with time zone,
  completed_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  created_at timestamp with time zone DEFAULT now(),
  referral_token text UNIQUE,
  referral_message_sent_at timestamp with time zone,
  google_review_link_sent boolean DEFAULT false,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.customers(id),
  CONSTRAINT referrals_referee_id_fkey FOREIGN KEY (referee_id) REFERENCES public.customers(id)
);
CREATE TABLE public.revenue_forecasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  forecast jsonb NOT NULL,
  confidence numeric DEFAULT 0.7,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_forecasts_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_forecasts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.revenue_guarantees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  guarantee_type text DEFAULT 'standard'::text CHECK (guarantee_type = ANY (ARRAY['standard'::text, 'premium'::text, 'custom'::text])),
  started_at timestamp with time zone NOT NULL,
  first_sale_deadline timestamp with time zone NOT NULL,
  first_sale_payout numeric DEFAULT 100,
  first_sale_met boolean DEFAULT false,
  first_sale_met_at timestamp with time zone,
  first_sale_payout_completed boolean DEFAULT false,
  first_sale_payout_at timestamp with time zone,
  first_sale_payout_id text,
  revenue_target numeric DEFAULT 1000,
  revenue_target_deadline timestamp with time zone NOT NULL,
  revenue_target_met boolean DEFAULT false,
  revenue_target_met_at timestamp with time zone,
  final_revenue numeric,
  free_service_activated boolean DEFAULT false,
  free_service_activated_at timestamp with time zone,
  free_service_ended_at timestamp with time zone,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'free_service'::text, 'cancelled'::text])),
  needs_manual_review boolean DEFAULT false,
  review_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_guarantees_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_guarantees_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.revenue_pattern_aggregates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pattern_key text NOT NULL UNIQUE,
  business_type text NOT NULL,
  industry text NOT NULL,
  offer_type text NOT NULL,
  channel text NOT NULL,
  conversion_rate numeric NOT NULL,
  avg_order_value numeric NOT NULL,
  sample_size integer NOT NULL,
  confidence_score numeric NOT NULL,
  best_message_template text,
  best_timing jsonb,
  best_customer_profile jsonb,
  trend_direction text,
  last_30_days_performance numeric,
  created_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_pattern_aggregates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.revenue_patterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  business_type text NOT NULL,
  industry text NOT NULL,
  offer_type text NOT NULL,
  offer_price numeric,
  offer_name text,
  channel text NOT NULL,
  channel_details jsonb,
  message_template text,
  message_type text,
  timing_pattern jsonb,
  conversion_rate numeric NOT NULL,
  avg_order_value numeric DEFAULT 0,
  customer_profile jsonb,
  campaign_context jsonb,
  sample_size integer DEFAULT 1,
  confidence_score numeric DEFAULT 0.1,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_patterns_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_patterns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.revenue_share_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  payment_intent_id text NOT NULL,
  total_amount numeric NOT NULL,
  business_amount numeric NOT NULL,
  launchfly_fee numeric NOT NULL,
  revenue_share_percentage numeric NOT NULL,
  plan_tier text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_share_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_share_transactions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.revenue_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  user_id uuid,
  verification_token text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'verified'::text, 'failed'::text, 'expired'::text])),
  verified_revenue numeric,
  stripe_account_id text,
  created_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT revenue_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_verifications_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT revenue_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  product_id text,
  amount numeric NOT NULL,
  currency text DEFAULT 'usd'::text,
  customer_email text,
  customer_name text,
  stripe_session_id text UNIQUE,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  order_id uuid,
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT sales_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.scheduled_guarantee_checks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  guarantee_id uuid,
  check_type text NOT NULL CHECK (check_type = ANY (ARRAY['first_sale'::text, 'revenue_target'::text, 'progress'::text])),
  scheduled_for timestamp with time zone NOT NULL,
  executed_at timestamp with time zone,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  result jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scheduled_guarantee_checks_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_guarantee_checks_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT scheduled_guarantee_checks_guarantee_id_fkey FOREIGN KEY (guarantee_id) REFERENCES public.revenue_guarantees(id)
);
CREATE TABLE public.service_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  service_type text NOT NULL CHECK (service_type = ANY (ARRAY['cleaning'::text, 'repair'::text, 'installation'::text, 'maintenance'::text, 'inspection'::text])),
  service_name text,
  appliance_type text,
  units_serviced integer DEFAULT 1,
  service_details text,
  amount numeric,
  currency text DEFAULT 'RM'::text,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'partial'::text, 'waived'::text])),
  address text,
  building_name text,
  area text,
  coordinates point,
  warranty_days integer DEFAULT 30,
  warranty_expires_at timestamp with time zone,
  warranty_claimed boolean DEFAULT false,
  warranty_claimed_at timestamp with time zone,
  service_interval_days integer DEFAULT 180,
  next_service_due_at timestamp with time zone,
  reminder_sent boolean DEFAULT false,
  reminder_sent_at timestamp with time zone,
  reminder_count integer DEFAULT 0,
  rebooking_initiated boolean DEFAULT false,
  rebooked_at timestamp with time zone,
  rebooked_service_id uuid,
  registered_via text DEFAULT 'sticker_scan'::text CHECK (registered_via = ANY (ARRAY['sticker_scan'::text, 'tech_register'::text, 'manual'::text, 'import'::text, 'booking_complete'::text])),
  registered_by text,
  service_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  feedback_request_sent_at timestamp with time zone,
  feedback_score integer CHECK (feedback_score >= 1 AND feedback_score <= 5),
  feedback_status text CHECK (feedback_status = ANY (ARRAY['positive'::text, 'negative'::text, 'pending'::text, 'no_response'::text])),
  feedback_text text,
  feedback_received_at timestamp with time zone,
  referral_asked_at timestamp with time zone,
  google_review_asked_at timestamp with time zone,
  CONSTRAINT service_records_pkey PRIMARY KEY (id),
  CONSTRAINT service_records_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT service_records_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT service_records_rebooked_fkey FOREIGN KEY (rebooked_service_id) REFERENCES public.service_records(id)
);
CREATE TABLE public.service_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_record_id uuid NOT NULL,
  business_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  scheduled_for timestamp with time zone NOT NULL,
  reminder_type text NOT NULL CHECK (reminder_type = ANY (ARRAY['due_soon'::text, 'due_now'::text, 'overdue'::text, 'warranty_expiring'::text, 'follow_up'::text])),
  sequence_number integer DEFAULT 1,
  channel text DEFAULT 'sms'::text CHECK (channel = ANY (ARRAY['sms'::text, 'whatsapp_template'::text, 'whatsapp_session'::text, 'email'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'delivered'::text, 'failed'::text, 'clicked'::text, 'booked'::text, 'cancelled'::text])),
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  clicked_at timestamp with time zone,
  booked_at timestamp with time zone,
  booking_id uuid,
  message_template text,
  message_sent text,
  cost numeric DEFAULT 0,
  cost_currency text DEFAULT 'USD'::text,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT service_reminders_service_record_fkey FOREIGN KEY (service_record_id) REFERENCES public.service_records(id),
  CONSTRAINT service_reminders_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT service_reminders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT service_reminders_booking_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.sessions (
  id text NOT NULL,
  business_id uuid,
  stage text DEFAULT 'initializing'::text CHECK (stage = ANY (ARRAY['pending'::text, 'initializing'::text, 'analyzing'::text, 'researching'::text, 'building'::text, 'generating'::text, 'finalizing'::text, 'complete'::text, 'error'::text])),
  progress integer DEFAULT 0,
  completed_steps ARRAY DEFAULT '{}'::text[],
  phone_number text,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  inngest_job_id uuid,
  completed_at timestamp with time zone,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT sessions_inngest_job_id_fkey FOREIGN KEY (inngest_job_id) REFERENCES public.inngest_jobs(id)
);
CREATE TABLE public.shared_ai_knowledge (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learning jsonb NOT NULL,
  contributor_id uuid,
  embedding USER-DEFINED,
  verified boolean DEFAULT false,
  success_count integer DEFAULT 0,
  failure_count integer DEFAULT 0,
  knowledge_timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT shared_ai_knowledge_pkey PRIMARY KEY (id),
  CONSTRAINT shared_ai_knowledge_contributor_id_fkey FOREIGN KEY (contributor_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.sms_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  user_id uuid,
  phone_number text NOT NULL,
  message_type text NOT NULL,
  message_content text NOT NULL,
  twilio_message_id text,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'delivered'::text, 'undelivered'::text])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  delivered_at timestamp with time zone,
  CONSTRAINT sms_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT sms_notifications_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT sms_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.social_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_id uuid,
  prospect_id uuid,
  platform text NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['post'::text, 'comment'::text, 'dm'::text, 'like'::text, 'follow'::text, 'connect'::text, 'join_group'::text, 'message'::text])),
  action_status text DEFAULT 'pending'::text CHECK (action_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'rate_limited'::text])),
  content text,
  target_url text,
  target_user text,
  response_received boolean DEFAULT false,
  response_sentiment text CHECK (response_sentiment = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text])),
  conversion_generated boolean DEFAULT false,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT social_actions_pkey PRIMARY KEY (id),
  CONSTRAINT social_actions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT social_actions_prospect_id_fkey FOREIGN KEY (prospect_id) REFERENCES public.prospects(id),
  CONSTRAINT social_actions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.social_campaigns(id)
);
CREATE TABLE public.social_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  platforms ARRAY NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'cancelled'::text])),
  estimated_reach integer DEFAULT 0,
  estimated_conversions integer DEFAULT 0,
  estimated_first_sale text,
  campaign_settings jsonb DEFAULT '{}'::jsonb,
  performance_metrics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT social_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.social_monitoring (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  platform text NOT NULL,
  keyword text NOT NULL,
  location text,
  monitoring_type text DEFAULT 'keyword'::text CHECK (monitoring_type = ANY (ARRAY['keyword'::text, 'hashtag'::text, 'mention'::text, 'competitor'::text])),
  is_active boolean DEFAULT true,
  last_checked timestamp with time zone,
  results_found integer DEFAULT 0,
  opportunities_created integer DEFAULT 0,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_monitoring_pkey PRIMARY KEY (id),
  CONSTRAINT social_monitoring_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.social_platform_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['reddit'::text, 'facebook'::text, 'linkedin'::text, 'twitter'::text, 'instagram'::text])),
  account_username text NOT NULL,
  account_id text,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  account_status text DEFAULT 'active'::text CHECK (account_status = ANY (ARRAY['active'::text, 'suspended'::text, 'rate_limited'::text, 'error'::text])),
  daily_action_count integer DEFAULT 0,
  daily_action_limit integer DEFAULT 100,
  last_action_at timestamp with time zone,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_platform_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT social_platform_accounts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.sticker_scans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  customer_phone text NOT NULL,
  source text DEFAULT 'warranty_sticker'::text,
  scanned_at timestamp with time zone DEFAULT now(),
  converted_to_customer boolean DEFAULT false,
  customer_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sticker_scans_pkey PRIMARY KEY (id),
  CONSTRAINT sticker_scans_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT sticker_scans_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.success_patterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  action_type text NOT NULL,
  action_details jsonb NOT NULL,
  outcome_data jsonb NOT NULL,
  context_data jsonb,
  success_score numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT success_patterns_pkey PRIMARY KEY (id),
  CONSTRAINT success_patterns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  whatsapp_number text,
  email text,
  category text,
  notes text,
  avg_response_hours numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.suppression_list (
  email text NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppression_list_pkey PRIMARY KEY (email)
);
CREATE TABLE public.template_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.template_performance_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  businesses_created integer DEFAULT 0,
  successful_businesses integer DEFAULT 0,
  total_revenue numeric DEFAULT 0,
  avg_time_to_first_sale numeric,
  period_success_rate numeric,
  period_avg_revenue numeric,
  confidence_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_performance_history_pkey PRIMARY KEY (id),
  CONSTRAINT template_performance_history_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id)
);
CREATE TABLE public.template_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  business_id uuid,
  user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  review_text text,
  business_revenue numeric,
  time_to_success integer,
  would_recommend boolean DEFAULT true,
  verified_purchase boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT template_reviews_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT template_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT template_reviews_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id)
);
CREATE TABLE public.template_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  business_id uuid,
  user_id uuid,
  customizations jsonb,
  actual_revenue numeric DEFAULT 0,
  actual_first_sale_hours integer,
  success_achieved boolean DEFAULT false,
  used_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT template_usage_pkey PRIMARY KEY (id),
  CONSTRAINT template_usage_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT template_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT template_usage_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id)
);
CREATE TABLE public.tool_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  tool_name text NOT NULL,
  success boolean DEFAULT true,
  error text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tool_usage_pkey PRIMARY KEY (id),
  CONSTRAINT tool_usage_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.weekly_digests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  week_start date NOT NULL,
  digest_data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_digests_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_digests_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.whatsapp_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  label text NOT NULL DEFAULT ''::text,
  provider text NOT NULL DEFAULT 'ultramsg'::text,
  instance_id text,
  token text,
  base_url text,
  api_key text,
  instance_name text,
  daily_limit integer NOT NULL DEFAULT 25,
  sends_today integer NOT NULL DEFAULT 0,
  last_reset_at timestamp with time zone NOT NULL DEFAULT now(),
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT whatsapp_instances_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_instances_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);