-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.acquisition_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  strategy jsonb NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'failed'::text])),
  channels_launched jsonb DEFAULT '[]'::jsonb,
  total_prospects integer DEFAULT 0,
  total_conversions integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  started_at timestamp with time zone DEFAULT now(),
  next_optimization_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT acquisition_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT acquisition_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ad_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  platform text NOT NULL,
  campaign_name text NOT NULL,
  budget numeric NOT NULL,
  targeting jsonb,
  ad_copy jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text])),
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  conversions integer DEFAULT 0,
  cost_spent numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ad_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT ad_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.ai_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  type character varying NOT NULL,
  icon character varying,
  message text NOT NULL,
  details text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_activities_pkey PRIMARY KEY (id),
  CONSTRAINT ai_activities_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_proof_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  subdomain text NOT NULL UNIQUE,
  metrics jsonb NOT NULL,
  sales_data jsonb DEFAULT '[]'::jsonb,
  testimonials jsonb DEFAULT '[]'::jsonb,
  verification_status text DEFAULT 'unverified'::text CHECK (verification_status = ANY (ARRAY['unverified'::text, 'verified'::text, 'stripe_verified'::text])),
  verified_revenue numeric,
  last_verified timestamp with time zone,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT business_proof_pages_pkey PRIMARY KEY (id),
  CONSTRAINT business_proof_pages_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  would_recommend boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT business_reviews_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT business_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.business_success_predictions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  success_probability numeric NOT NULL,
  projected_revenue numeric NOT NULL,
  projected_timeframe_days integer,
  based_on_patterns integer,
  confidence_level text,
  recommendations jsonb,
  actual_outcome numeric,
  prediction_accuracy numeric,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  CONSTRAINT business_success_predictions_pkey PRIMARY KEY (id),
  CONSTRAINT business_success_predictions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  business_type text NOT NULL,
  industry text NOT NULL,
  proven_revenue numeric NOT NULL,
  success_rate numeric NOT NULL,
  time_to_first_sale integer NOT NULL,
  guarantee_confidence numeric NOT NULL,
  business_model jsonb NOT NULL,
  marketing_playbook jsonb NOT NULL,
  operational_requirements jsonb NOT NULL,
  success_metrics jsonb NOT NULL,
  risk_factors jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'draft'::text, 'deprecated'::text])),
  usage_count integer DEFAULT 0,
  actual_performance jsonb,
  last_performance_update timestamp with time zone,
  last_confidence_update timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  subdomain text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'generating'::text, 'ready'::text, 'failed'::text])),
  session_id text UNIQUE,
  phone_number text,
  completed_onboarding boolean DEFAULT false,
  launch_date timestamp with time zone,
  trial_ends_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  form_data jsonb NOT NULL,
  business_data jsonb,
  views integer DEFAULT 0,
  first_sale_date timestamp with time zone,
  total_revenue numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_sale_date timestamp with time zone,
  growth_data jsonb,
  latest_campaign_review jsonb,
  latest_email_campaign jsonb,
  latest_email_batch jsonb,
  opportunity_data jsonb,
  total_leads integer DEFAULT 0,
  total_visitors integer DEFAULT 0,
  projected_revenue numeric DEFAULT 0,
  last_growth_campaign_at timestamp with time zone,
  guarantee_start_at timestamp with time zone,
  first_payment_at timestamp with time zone,
  guarantee_48h_status text DEFAULT 'pending'::text CHECK (guarantee_48h_status = ANY (ARRAY['pending'::text, 'met'::text, 'missed'::text, 'paid'::text])),
  guarantee_60d_status text DEFAULT 'pending'::text CHECK (guarantee_60d_status = ANY (ARRAY['pending'::text, 'met'::text, 'extended'::text, 'failed'::text])),
  guarantee_last_checked_at timestamp with time zone,
  guarantee_48h_payout_id text,
  guarantee_48h_payout_amount numeric DEFAULT 100,
  plan_tier text DEFAULT 'starter'::text CHECK (plan_tier = ANY (ARRAY['starter'::text, 'pro'::text, 'scale'::text])),
  rev_share_percent numeric DEFAULT 0,
  stripe_connect_account_id text,
  work_free_mode boolean DEFAULT false,
  model text,
  assets jsonb,
  strategy_plan jsonb,
  email_ramp_stage integer DEFAULT 0,
  manual_approval_required boolean DEFAULT true,
  approved_at timestamp with time zone,
  ai_objections_handled integer DEFAULT 0,
  ai_response_rate numeric DEFAULT 0.00,
  ai_conversation_count integer DEFAULT 0,
  template_id uuid,
  ai_agent_enabled boolean DEFAULT true,
  CONSTRAINT businesses_pkey PRIMARY KEY (id),
  CONSTRAINT businesses_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id),
  CONSTRAINT businesses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text,
  sent_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.cart_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  customer_email text,
  customer_name text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_amount numeric DEFAULT 0,
  last_activity_at timestamp with time zone DEFAULT now(),
  abandoned_at timestamp with time zone,
  recovery_emails_sent integer DEFAULT 0,
  recovered boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT cart_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.clicks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  email_id uuid,
  business_id uuid NOT NULL,
  campaign_id uuid,
  dest_url text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clicks_pkey PRIMARY KEY (id),
  CONSTRAINT clicks_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT clicks_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id),
  CONSTRAINT clicks_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.conversion_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  session_id text,
  event_type text NOT NULL,
  product_id uuid,
  customer_email text,
  value numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversion_events_pkey PRIMARY KEY (id),
  CONSTRAINT conversion_events_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT conversion_events_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.conversion_intelligence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_type text NOT NULL,
  industry text NOT NULL,
  query_hash text NOT NULL UNIQUE,
  top_strategies jsonb NOT NULL,
  timing_insights jsonb,
  message_insights jsonb,
  cache_expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  hit_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  last_accessed timestamp with time zone DEFAULT now(),
  CONSTRAINT conversion_intelligence_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  customer_email text NOT NULL,
  customer_name text NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  testimonial_text text NOT NULL,
  order_id uuid,
  verified boolean DEFAULT false,
  verification_method text,
  created_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  CONSTRAINT customer_testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT customer_testimonials_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  email text NOT NULL,
  first_name text,
  last_name text,
  phone text,
  total_spent numeric DEFAULT 0,
  order_count integer DEFAULT 0,
  first_order_date timestamp with time zone,
  last_order_date timestamp with time zone,
  lifetime_value numeric DEFAULT 0,
  accepts_marketing boolean DEFAULT true,
  marketing_source text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.discount_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  code text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['percentage'::text, 'fixed_amount'::text])),
  value numeric NOT NULL,
  minimum_order_amount numeric DEFAULT 0,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_codes_pkey PRIMARY KEY (id),
  CONSTRAINT discount_codes_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.email_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  prospect_email text NOT NULL,
  message_type text NOT NULL CHECK (message_type = ANY (ARRAY['initial'::text, 'objection'::text, 'ai_response'::text, 'follow_up'::text])),
  content text NOT NULL,
  objection_type text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT email_conversations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.email_outreach (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  prospect_id character varying NOT NULL,
  email_type character varying NOT NULL,
  subject character varying,
  content text,
  status character varying DEFAULT 'sent'::character varying,
  sent_at timestamp with time zone,
  response_received boolean DEFAULT false,
  meeting_scheduled boolean DEFAULT false,
  converted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_outreach_pkey PRIMARY KEY (id),
  CONSTRAINT email_outreach_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.email_replies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_id uuid,
  business_id uuid NOT NULL,
  from_email text,
  body text,
  sentiment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_replies_pkey PRIMARY KEY (id),
  CONSTRAINT email_replies_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT email_replies_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id)
);
CREATE TABLE public.emails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_id uuid,
  to_email text NOT NULL,
  subject text,
  provider text,
  provider_message_id text,
  bounce boolean DEFAULT false,
  complaint boolean DEFAULT false,
  suppressed boolean DEFAULT false,
  clicked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT emails_pkey PRIMARY KEY (id),
  CONSTRAINT emails_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT emails_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.follow_up_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  prospect_email text NOT NULL,
  objection_type text,
  follow_up_date timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text, 'failed'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT follow_up_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT follow_up_tasks_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.fulfillment_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  content_type text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  access_count integer DEFAULT 0,
  last_accessed_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillment_content_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillment_content_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.fulfillment_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback_text text,
  improvement_suggestions text,
  would_recommend boolean,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillment_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillment_feedback_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.fulfillment_followups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  follow_up_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'completed'::text, 'skipped'::text])),
  scheduled_for timestamp with time zone NOT NULL,
  sent_at timestamp with time zone,
  response_received boolean DEFAULT false,
  response_content text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillment_followups_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillment_followups_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.fulfillments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  fulfillment_type text NOT NULL,
  delivered_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_value numeric DEFAULT 0,
  completed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fulfillments_pkey PRIMARY KEY (id),
  CONSTRAINT fulfillments_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.growth_experiments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  experiment_type character varying NOT NULL,
  experiment_data jsonb NOT NULL,
  status character varying DEFAULT 'running'::character varying,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  results jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT growth_experiments_pkey PRIMARY KEY (id),
  CONSTRAINT growth_experiments_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.growth_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_type text NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'failed'::text])),
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  metrics jsonb DEFAULT '{"conversions": 0, "leads_generated": 0, "revenue_generated": 0}'::jsonb,
  CONSTRAINT growth_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT growth_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.guarantee_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  payout_id text NOT NULL,
  amount numeric NOT NULL,
  reason text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  stripe_payout_id text,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT guarantee_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT guarantee_payouts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.idempotency (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT idempotency_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inngest_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  job_type character varying NOT NULL,
  event_name character varying NOT NULL,
  event_data jsonb NOT NULL,
  status character varying DEFAULT 'queued'::character varying,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inngest_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT inngest_jobs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketing_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  campaign_data jsonb NOT NULL,
  channel character varying NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketplace_listings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  platform text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  pricing jsonb NOT NULL,
  tags ARRAY,
  status text DEFAULT 'pending_approval'::text CHECK (status = ANY (ARRAY['pending_approval'::text, 'active'::text, 'paused'::text, 'rejected'::text])),
  orders_received integer DEFAULT 0,
  total_earnings numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketplace_listings_pkey PRIMARY KEY (id),
  CONSTRAINT marketplace_listings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid,
  product_name text NOT NULL,
  product_price numeric NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_email text NOT NULL,
  customer_name text,
  customer_phone text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'fulfilled'::text, 'refunded'::text, 'abandoned'::text])),
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  shipping_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  stripe_session_id text UNIQUE,
  cart_token text UNIQUE,
  abandoned_at timestamp with time zone,
  recovery_email_sent_at timestamp with time zone,
  recovered_at timestamp with time zone,
  shipping_address jsonb,
  billing_address jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.outreach_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_type text NOT NULL,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'completed'::text])),
  total_prospects integer DEFAULT 0,
  email_templates jsonb,
  metrics jsonb DEFAULT '{"sent": 0, "opened": 0, "clicked": 0, "replied": 0}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  last_batch_sent_at timestamp with time zone,
  CONSTRAINT outreach_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT outreach_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  product_id uuid,
  order_id uuid,
  customer_email text NOT NULL,
  customer_name text,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  content text,
  verified_purchase boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  approved boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT product_reviews_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  compare_at_price numeric,
  inventory_count integer DEFAULT 999,
  sales_count integer DEFAULT 0,
  conversion_rate numeric DEFAULT 0.00,
  image_url text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'draft'::text, 'archived'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  plan text DEFAULT 'trial'::text CHECK (plan = ANY (ARRAY['trial'::text, 'starter'::text, 'growth'::text, 'scale'::text])),
  phone_number text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.prospects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name character varying,
  email character varying,
  company character varying,
  industry character varying,
  company_size character varying,
  linkedin_url text,
  title character varying,
  source character varying,
  status character varying DEFAULT 'discovered'::character varying,
  contacted_at timestamp with time zone,
  last_response_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  last_objection_type text,
  last_ai_response text,
  objection_count integer DEFAULT 0,
  conversation_count integer DEFAULT 0,
  platform text CHECK (platform = ANY (ARRAY['reddit'::text, 'facebook'::text, 'linkedin'::text, 'twitter'::text, 'instagram'::text, 'email'::text])),
  platform_username text,
  platform_user_id text,
  profile_url text,
  engagement_score integer DEFAULT 0 CHECK (engagement_score >= 0 AND engagement_score <= 100),
  conversion_status text DEFAULT 'discovered'::text CHECK (conversion_status = ANY (ARRAY['discovered'::text, 'contacted'::text, 'engaged'::text, 'qualified'::text, 'converted'::text, 'lost'::text])),
  last_engagement timestamp with time zone,
  contact_attempts integer DEFAULT 0,
  notes text,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT prospects_pkey PRIMARY KEY (id),
  CONSTRAINT prospects_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.public_metrics (
  id text NOT NULL,
  metrics jsonb NOT NULL,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT public_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.revenue_pattern_aggregates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pattern_key text NOT NULL UNIQUE,
  business_type text NOT NULL,
  industry text NOT NULL,
  offer_type text NOT NULL,
  channel text NOT NULL,
  conversion_rate numeric NOT NULL,
  avg_order_value numeric NOT NULL,
  sample_size integer NOT NULL,
  confidence_score numeric NOT NULL,
  best_message_template text,
  best_timing jsonb,
  best_customer_profile jsonb,
  trend_direction text,
  last_30_days_performance numeric,
  created_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_pattern_aggregates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.revenue_patterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  business_type text NOT NULL,
  industry text NOT NULL,
  offer_type text NOT NULL,
  offer_price numeric,
  offer_name text,
  channel text NOT NULL,
  channel_details jsonb,
  message_template text,
  message_type text,
  timing_pattern jsonb,
  conversion_rate numeric NOT NULL,
  avg_order_value numeric DEFAULT 0,
  customer_profile jsonb,
  campaign_context jsonb,
  sample_size integer DEFAULT 1,
  confidence_score numeric DEFAULT 0.1,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_patterns_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_patterns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.revenue_share_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  payment_intent_id text NOT NULL,
  total_amount numeric NOT NULL,
  business_amount numeric NOT NULL,
  launchfly_fee numeric NOT NULL,
  revenue_share_percentage numeric NOT NULL,
  plan_tier text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT revenue_share_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_share_transactions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.revenue_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  user_id uuid,
  verification_token text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'verified'::text, 'failed'::text, 'expired'::text])),
  verified_revenue numeric,
  stripe_account_id text,
  created_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT revenue_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT revenue_verifications_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT revenue_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid,
  product_id text,
  amount numeric NOT NULL,
  currency text DEFAULT 'usd'::text,
  customer_email text,
  customer_name text,
  stripe_session_id text UNIQUE,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  order_id uuid,
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT sales_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.sessions (
  id text NOT NULL,
  business_id uuid,
  stage text DEFAULT 'initializing'::text CHECK (stage = ANY (ARRAY['pending'::text, 'initializing'::text, 'analyzing'::text, 'researching'::text, 'building'::text, 'generating'::text, 'finalizing'::text, 'complete'::text, 'error'::text])),
  progress integer DEFAULT 0,
  completed_steps ARRAY DEFAULT '{}'::text[],
  phone_number text,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  inngest_job_id uuid,
  completed_at timestamp with time zone,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT sessions_inngest_job_id_fkey FOREIGN KEY (inngest_job_id) REFERENCES public.inngest_jobs(id)
);
CREATE TABLE public.social_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  campaign_id uuid,
  prospect_id uuid,
  platform text NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['post'::text, 'comment'::text, 'dm'::text, 'like'::text, 'follow'::text, 'connect'::text, 'join_group'::text, 'message'::text])),
  action_status text DEFAULT 'pending'::text CHECK (action_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'rate_limited'::text])),
  content text,
  target_url text,
  target_user text,
  response_received boolean DEFAULT false,
  response_sentiment text CHECK (response_sentiment = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text])),
  conversion_generated boolean DEFAULT false,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT social_actions_pkey PRIMARY KEY (id),
  CONSTRAINT social_actions_prospect_id_fkey FOREIGN KEY (prospect_id) REFERENCES public.prospects(id),
  CONSTRAINT social_actions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.social_campaigns(id),
  CONSTRAINT social_actions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.social_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  platforms ARRAY NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'cancelled'::text])),
  estimated_reach integer DEFAULT 0,
  estimated_conversions integer DEFAULT 0,
  estimated_first_sale text,
  campaign_settings jsonb DEFAULT '{}'::jsonb,
  performance_metrics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT social_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.social_monitoring (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  platform text NOT NULL,
  keyword text NOT NULL,
  location text,
  monitoring_type text DEFAULT 'keyword'::text CHECK (monitoring_type = ANY (ARRAY['keyword'::text, 'hashtag'::text, 'mention'::text, 'competitor'::text])),
  is_active boolean DEFAULT true,
  last_checked timestamp with time zone,
  results_found integer DEFAULT 0,
  opportunities_created integer DEFAULT 0,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_monitoring_pkey PRIMARY KEY (id),
  CONSTRAINT social_monitoring_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.social_platform_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['reddit'::text, 'facebook'::text, 'linkedin'::text, 'twitter'::text, 'instagram'::text])),
  account_username text NOT NULL,
  account_id text,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  account_status text DEFAULT 'active'::text CHECK (account_status = ANY (ARRAY['active'::text, 'suspended'::text, 'rate_limited'::text, 'error'::text])),
  daily_action_count integer DEFAULT 0,
  daily_action_limit integer DEFAULT 100,
  last_action_at timestamp with time zone,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_platform_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT social_platform_accounts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.suppression_list (
  email text NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppression_list_pkey PRIMARY KEY (email)
);
CREATE TABLE public.template_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.template_performance_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  businesses_created integer DEFAULT 0,
  successful_businesses integer DEFAULT 0,
  total_revenue numeric DEFAULT 0,
  avg_time_to_first_sale numeric,
  period_success_rate numeric,
  period_avg_revenue numeric,
  confidence_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_performance_history_pkey PRIMARY KEY (id),
  CONSTRAINT template_performance_history_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id)
);
CREATE TABLE public.template_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  business_id uuid,
  user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  review_text text,
  business_revenue numeric,
  time_to_success integer,
  would_recommend boolean DEFAULT true,
  verified_purchase boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT template_reviews_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id),
  CONSTRAINT template_reviews_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.template_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  business_id uuid,
  user_id uuid,
  customizations jsonb,
  actual_revenue numeric DEFAULT 0,
  actual_first_sale_hours integer,
  success_achieved boolean DEFAULT false,
  used_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT template_usage_pkey PRIMARY KEY (id),
  CONSTRAINT template_usage_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.business_templates(id),
  CONSTRAINT template_usage_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);