import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://js.stripe.com/v3/"></script>
      </head>
      <body>
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `if (typeof window !== 'undefined' && window.Stripe) { window.stripe = window.Stripe('${process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}'); }`,
          }}
        />
      </body>
    </html>
  );
}
